# Form implementation generated from reading ui file 'ui/confgui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys
import os


def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS2
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)


class Ui_FormSettings(object):
    def setupUi(self, FormSettings):
        FormSettings.setObjectName("FormSettings")
        FormSettings.resize(542, 476)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("img"+os.sep+"gear.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        FormSettings.setWindowIcon(icon)
        self.aceptarButton = QtWidgets.QPushButton(parent=FormSettings)
        self.aceptarButton.setGeometry(QtCore.QRect(420, 420, 101, 41))
        self.aceptarButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.aceptarButton.setObjectName("aceptarButton")
        self.cancelarButton = QtWidgets.QPushButton(parent=FormSettings)
        self.cancelarButton.setGeometry(QtCore.QRect(300, 420, 101, 41))
        self.cancelarButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancelarButton.setObjectName("cancelarButton")
        self.marco1 = QtWidgets.QFrame(parent=FormSettings)
        self.marco1.setGeometry(QtCore.QRect(20, 88, 501, 84))
        self.marco1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.marco1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.marco1.setObjectName("marco1")
        self.label1 = QtWidgets.QLabel(parent=self.marco1)
        self.label1.setGeometry(QtCore.QRect(20, 10, 191, 16))
        self.label1.setObjectName("label1")
        self.themeSelBox = QtWidgets.QComboBox(parent=self.marco1)
        self.themeSelBox.setGeometry(QtCore.QRect(50, 44, 401, 24))
        self.themeSelBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.themeSelBox.setObjectName("themeSelBox")
        self.marco2 = QtWidgets.QFrame(parent=FormSettings)
        self.marco2.setGeometry(QtCore.QRect(20, 182, 501, 221))
        self.marco2.setStyleSheet("")
        self.marco2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.marco2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.marco2.setObjectName("marco2")
        self.label2 = QtWidgets.QLabel(parent=self.marco2)
        self.label2.setGeometry(QtCore.QRect(20, 10, 191, 16))
        self.label2.setObjectName("label2")
        self.borrarTemaButton = QtWidgets.QPushButton(parent=self.marco2)
        self.borrarTemaButton.setGeometry(QtCore.QRect(240, 160, 121, 28))
        self.borrarTemaButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.borrarTemaButton.setObjectName("borrarTemaButton")
        self.fontColorButton = QtWidgets.QPushButton(parent=self.marco2)
        self.fontColorButton.setGeometry(QtCore.QRect(150, 170, 51, 28))
        self.fontColorButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.fontColorButton.setText("")
        self.fontColorButton.setObjectName("fontColorButton")
        self.color2Button = QtWidgets.QPushButton(parent=self.marco2)
        self.color2Button.setGeometry(QtCore.QRect(150, 130, 51, 28))
        self.color2Button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.color2Button.setText("")
        self.color2Button.setObjectName("color2Button")
        self.color1Button = QtWidgets.QPushButton(parent=self.marco2)
        self.color1Button.setGeometry(QtCore.QRect(150, 90, 51, 28))
        self.color1Button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.color1Button.setText("")
        self.color1Button.setObjectName("color1Button")
        self.lineCol1 = QtWidgets.QLineEdit(parent=self.marco2)
        self.lineCol1.setGeometry(QtCore.QRect(40, 90, 101, 28))
        self.lineCol1.setObjectName("lineCol1")
        self.lineCol2 = QtWidgets.QLineEdit(parent=self.marco2)
        self.lineCol2.setGeometry(QtCore.QRect(40, 130, 101, 28))
        self.lineCol2.setObjectName("lineCol2")
        self.lineFontCol = QtWidgets.QLineEdit(parent=self.marco2)
        self.lineFontCol.setGeometry(QtCore.QRect(40, 170, 101, 28))
        self.lineFontCol.setObjectName("lineFontCol")
        self.nombreInput = QtWidgets.QLineEdit(parent=self.marco2)
        self.nombreInput.setGeometry(QtCore.QRect(100, 50, 261, 28))
        self.nombreInput.setObjectName("nombreInput")
        self.labelNombre = QtWidgets.QLabel(parent=self.marco2)
        self.labelNombre.setGeometry(QtCore.QRect(40, 60, 51, 16))
        self.labelNombre.setObjectName("labelNombre")
        self.infoBrowser = QtWidgets.QTextBrowser(parent=self.marco2)
        self.infoBrowser.setGeometry(QtCore.QRect(375, 51, 111, 151))
        self.infoBrowser.setObjectName("infoBrowser")
        self.editorNotifications = QtWidgets.QLabel(parent=self.marco2)
        self.editorNotifications.setGeometry(QtCore.QRect(130, 8, 351, 21))
        self.editorNotifications.setStyleSheet("color: red")
        self.editorNotifications.setText("")
        self.editorNotifications.setObjectName("editorNotifications")
        self.marco0 = QtWidgets.QFrame(parent=FormSettings)
        self.marco0.setGeometry(QtCore.QRect(20, 20, 501, 58))
        self.marco0.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.marco0.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.marco0.setObjectName("marco0")
        self.label0 = QtWidgets.QLabel(parent=self.marco0)
        self.label0.setGeometry(QtCore.QRect(20, 12, 191, 16))
        self.label0.setObjectName("label0")
        self.trayCheckBox = QtWidgets.QCheckBox(parent=self.marco0)
        self.trayCheckBox.setGeometry(QtCore.QRect(440, 10, 41, 21))
        self.trayCheckBox.setObjectName("trayCheckBox")
        self.label02 = QtWidgets.QLabel(parent=self.marco0)
        self.label02.setGeometry(QtCore.QRect(20, 30, 441, 16))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Thin")
        font.setPointSize(8)
        font.setItalic(False)
        self.label02.setFont(font)
        self.label02.setObjectName("label02")

        self.retranslateUi(FormSettings)
        QtCore.QMetaObject.connectSlotsByName(FormSettings)

    def retranslateUi(self, FormSettings):
        _translate = QtCore.QCoreApplication.translate
        FormSettings.setWindowTitle(_translate("FormSettings", "Form"))
        self.aceptarButton.setText(_translate("FormSettings", "Aceptar"))
        self.cancelarButton.setText(_translate("FormSettings", "Cancelar"))
        self.label1.setText(_translate("FormSettings", "Elige el tema que deseas usar :"))
        self.label2.setText(_translate("FormSettings", "Editor de tema:"))
        self.borrarTemaButton.setText(_translate("FormSettings", "Borrar tema"))
        self.fontColorButton.setToolTip(_translate("FormSettings", "Editar color de las fuentes"))
        self.color2Button.setToolTip(_translate("FormSettings", "Editar segundo color"))
        self.color1Button.setToolTip(_translate("FormSettings", "Editar primer color"))
        self.lineCol1.setPlaceholderText(_translate("FormSettings", "Color1 #rrggbb"))
        self.lineCol2.setPlaceholderText(_translate("FormSettings", "Color2 #rrggbb"))
        self.lineFontCol.setPlaceholderText(_translate("FormSettings", "Font Color #rrggbb"))
        self.labelNombre.setText(_translate("FormSettings", "Nombre:"))
        self.infoBrowser.setHtml(_translate("FormSettings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Para crear un tema nuevo que aparecerá en el selector, añade un <span style=\" font-weight:600;\">nombre nuevo</span>, <span style=\" font-weight:600;\">edita los colores</span> y pulsa<span style=\" font-weight:600;\"> \'Aceptar\'</span> .</p></body></html>"))
        self.label0.setText(_translate("FormSettings", "¿Minimizar a la bandeja al cerrar?"))
        self.trayCheckBox.setToolTip(_translate("FormSettings", "Activar/Desactivar opcion de bandeja de sistema."))
        self.trayCheckBox.setText(_translate("FormSettings", "No"))
        self.label02.setText(_translate("FormSettings", "La configuración tendrá efecto cuanvuelva iniciar la aplicación"))
